#+title: Ärendehantering
#+subtitle: <2023-05-02 08:51>
#+date: <2023-05-02 08:51:15>
#+author: Johan Sandén
#+email: johan.sanden@gmail.com
#+HTML_HEAD:<link rel="stylesheet" type="text/css" href="../../../css/style.css" />
#+INCLUDE: ../../../__blog_meny.org

När man inte har ett system som automatiserar eller någon rutin för att hur man
ska hantera ärenden så är kommunikation viktigt. Jag är själv dålig på att komma
ihåg det här. Idag hände det igen och det är inte första gången.

Det kommer ett mail till hela gruppen. Den här gången försökte jag kommunicera
ut till hela gruppen att jag håller på med det och efter att ha petat runt lite
så börjar jag ställa frågor i de kanalerna vi har....tyst som i graven.

Jag ställer mer frågor och riktar dem till specifika personer. Tyst som i
graven. ...jag skickar frågorna till personer som jag vet är på plats i deras
privata kanaler. Tystnad...

Plötsligt kommer det ett var till all och hen som skickade ärendet från en i vår
grupp. Det i sig är ju skitbra. Men nu har jag slagit ihjäl en halvtimme i
onödan.

GAAAHHHHhhh
------------
