#+title: Sanningen i konsten.
#+subtitle: <2023-10-12 04:44>
#+date: <2023-10-12 04:44:12>
#+author: Johan Sandén
#+email: johan.sanden@gmail.com
#+HTML_HEAD:<link rel="stylesheet" type="text/css" href="../../../css/style.css" />
#+INCLUDE: ../../../__blog_meny.org

När man jobbar konstnärligt så ber man om att få underhålla någon. För mig, som
musiker, en låtjävel i taget. Det jag hoppas på är att inspirera. Det finns
ingen sanning i varken text eller musik. Som musiker målar jag åhörarens tid, så
länge musiken pågår.

Som jag ser det; söker man ren sanning ska man läsa "Tractatus
logico-philosophicus" av Ludwig Wittgenstein eller "Principia Mathematica" av
Alfred North Whitehead och Bertrand Russell. All annan information som människan
producerat för andra människors är mätningar, gissningar eller åsikter.

Konsten och kulturen är att vara just vilse, att planlöst och naivt smaka på
allt för att sen blanda och ge tillbaka efter tycke och smak. Skulle min konst
någon enstaka gång snubbla in på sanningens marmorgolv är det av ren slump.

------------
