#+title: Blåbrun kan vara en politisk färg.
#+subtitle: <2022-07-14 07:27>
#+date: <2022-07-14 07:27:36>
#+author: Johan Sandén
#+email: johan.sanden@gmail.com
#+HTML_HEAD:<link rel="stylesheet" type="text/css" href="../../../css/style.css" />
#+INCLUDE: ../../../__blog_meny.org

Ibland är färger som röd, grön, blåbrun osv. politiska. Men oftast är färgerna
inte politiska. Himlen är blå på dagen för att de korta våglängderna sprids
bäst. Gräset och träden är gröna för de innehåller klorofyll. Blodet är rött för
att det innehåller hemoglobin. Färgen på våra tapeter har den färg de har för att
min fru tycker det är snyggt.\\
\\
Den sista tiden har Lars Beckman och andra klimatförnekare från det blåbruna
blocket kommit med det idiotiska påståenden att färgerna på väderkartorna de ser
i medier är färgade med politiska kritor.\\
\\
Det blåbruna blockets politiker predikar detta till sin kör för att få dem att
sjunga. Även om det i deras fall låter som ett som ett fyllebrölande. De gör det
inte främst för att reta mig utan för reta upp sin mob som är en stor del av
deras egen väljarbas. På så sätt kan de behålla den och, hoppas de, kanske öka
neandertalarna[fn:neandertalarna:Förlåt jag har har egentligen inget emot
neandertalare.] i antal.

------------
