#+title: Var är valfläsket?
#+subtitle: <2025-11-12 20:20>
#+date: <2025-11-12 10:20:20>
#+author: Johan Sandén
#+email: johan.sanden@gmail.com
#+HTML_HEAD:<link rel="stylesheet" type="text/css" href="../../../css/style.css" />
#+INCLUDE: ../../../__blog_meny.org

Jag fattar inte. 2025 går mot sitt slut och det är val nästa år. Borgarna ligger
drygt åtta procent efter, KD klamrar sig fast vid gärdsgården, och Liberalerna
de ligger i gräset brevid som ett fyllo och sover med sina 2.2%.

SD har gått om Moderaterna och regeringssamarbetet knakar som en gammal skev
dassdörr i Albanien.

Så nu undrar jag, VAR ÄR VALFLÄSKET? De kommer då och då med sin trötta och
världfrånvända rasistinlägg och motioner, men det borde ju osa som dimman över
Lützen vid det här laget. Normalt brukar man få öppna balkongdörren mot
verkligheten på vid gavel för att vädra ut bacondoften ur huset.

Vad väntar man på? Eller har man supit upp och förskingrat hela kaffekassan?
Hoppas man att 10% av väljarna spontant får hjärnblödning i valbåsen?

------------
