#+title: Företag i samhället.
#+subtitle: <2025-11-15 10:18>
#+date: <2025-11-15 10:18:40>
#+author: Johan Sandén
#+email: johan.sanden@gmail.com
#+HTML_HEAD:<link rel="stylesheet" type="text/css" href="../../../css/style.css" />
#+INCLUDE: ../../../__blog_meny.org

Företag skulle trycka egna pengar om de bara kunde komma undan med det. Tack och
lov kan de inte det än.

Företagen konkurerar med varandra om medborgarnas pengar och resurser och där de
går fram sliter de på samhället, trampar ner och förstör.

I politiska möten och beslut om it-säkerhet, anonymitet och övervakning ser vi
gång på gång hur staten skyddar företagen från medborgare, när det borde vara
precis tvärtom.

Företag behöver nästan inga "rättigheter" i samhället alls. De behöver regler
och skyldigheter. Företagens ska hägnas in och borde kontrolleras och övervakas
med stenhårda, korta tömmar till mycket större utsträckning än vad som görs
idag. Samhället och demokratin tillhör människorna, inte företag.

Att företagen vill hålla hemligheter för konkurrenter är förståeligt. Men för
staten ska det inte finnas något som heter "företagshemligheter". Inte gentemot
regering, riksdag, polis och statliga åklagare, skatteverket och andra
myndigheter som reglerar aspekter av samhället där företagen konkurrerar om våra
resurser. Där borde allt vara glasklart och transparent.

Demokratin och samhället finns för att skydda människor, bland annat från
företag. Demokrati och samhälles politiker ska inte skydda företag från
medborgare. Vi medborgare har rätt till skydd från företag.

------------
